import { nationalite } from "./nationalite";

// COPY public.nationalite FROM 'C:\Users\Hp\Desktop\liste.csv' WITH CSV DELIMITER ';'
export const liste_nat :nationalite[]  = [
    { codeNationalite:1, nationalite: 'Afghanistan' },
    { codeNationalite:2, nationalite: 'Afrique_Centrale' },
    { codeNationalite:3, nationalite: 'Afrique du Sud' },
    { codeNationalite:4, nationalite: 'Albanie'  },
    { codeNationalite:5, nationalite: 'Algerie' },
    { codeNationalite:6, nationalite: 'Allemagne' },
    { codeNationalite:7, nationalite: 'Andorre' },
    { codeNationalite:8, nationalite: 'Angola'  },
    { codeNationalite:9, nationalite: 'Arabie Saoudite' },
    { codeNationalite:10, nationalite: 'Argentine' },
    { codeNationalite:11, nationalite: 'Aruba' },
    { codeNationalite:12, nationalite: 'Armenie' },
    { codeNationalite:13, nationalite: 'Australie' },
    { codeNationalite:14, nationalite: 'Autriche'  },
    { codeNationalite:15, nationalite: 'Azerbaïdjan' },
    { codeNationalite:16, nationalite: 'Bahamas' },
    { codeNationalite:17, nationalite: 'Bahreïn' },
    { codeNationalite:18, nationalite: 'Bangladesh'  },
    { codeNationalite:19, nationalite: 'Barbade' },
    { codeNationalite:20, nationalite: 'Bélarus' },
    { codeNationalite:21, nationalite: 'Birmanie' },
    { codeNationalite:22, nationalite: 'Belgique'  },
    { codeNationalite:23, nationalite: 'Belize' },
    { codeNationalite:24, nationalite: 'Bénin' },
    { codeNationalite:25, nationalite: 'Bhutan' },
    { codeNationalite:26, nationalite: 'Bermudes'  },
    { codeNationalite:27, nationalite: 'Bolivie' },
    { codeNationalite:28, nationalite: 'Botswana' },
    { codeNationalite:29, nationalite: 'Bhoutan' },
    { codeNationalite:30, nationalite: 'Boznie_Herzegovine' },
    { codeNationalite:31, nationalite: 'Bresil' },
    { codeNationalite:32, nationalite: 'Brunei' },  
    { codeNationalite:33, nationalite: 'Bulgarie' },
    { codeNationalite:34, nationalite: 'Burkina_Faso' },
    { codeNationalite:35, nationalite: 'Burundi' },
    { codeNationalite:36, nationalite: 'Caiman' },
    { codeNationalite:37, nationalite: 'Cambodge' },
    { codeNationalite:38, nationalite: 'Cameroun' },
    { codeNationalite:39, nationalite: 'Canada' },
    { codeNationalite:40, nationalite: 'Canaries' },
    { codeNationalite:41, nationalite: 'Cap_vert' },
    { codeNationalite:42, nationalite: 'Chili' },
    { codeNationalite:43, nationalite: 'Chine' },
    { codeNationalite:44, nationalite: 'Chypre' },
    { codeNationalite:45, nationalite: 'Colombie'  },
    { codeNationalite:46, nationalite: 'Comores' },
    { codeNationalite:47, nationalite: 'Congo' },
    { codeNationalite:48, nationalite: 'Congo_democratique' },
    { codeNationalite:49, nationalite: 'Cook' },
    { codeNationalite:50, nationalite: 'Central African' },
    { codeNationalite:51, nationalite: 'Chad' },
    { codeNationalite:52, nationalite: 'Costa_Rica' },
    { codeNationalite:53, nationalite: 'Cote_d_Ivoire' },
    { codeNationalite:232, nationalite: 'Corée du nord' },
    { codeNationalite:54, nationalite: 'Croatie' },
    { codeNationalite:55, nationalite: 'Cuba' },
    { codeNationalite:56, nationalite :'Danemark'},
    { codeNationalite:57, nationalite :"Djibouti"},
    { codeNationalite:58, nationalite :'Dominique'},
    { codeNationalite:59, nationalite :'Egypte'},
    { codeNationalite:60, nationalite :'Emirats_Arabes_Unis'},
    { codeNationalite:61, nationalite :'Equateur' },
    { codeNationalite:62, nationalite :'Erythree' },
    { codeNationalite:63, nationalite :"Espagne"},
    { codeNationalite:64, nationalite :"Estonie"},
    { codeNationalite:65, nationalite :"Etats_Unis"},
    { codeNationalite:66, nationalite :'Ethiopie' },
    { codeNationalite:67, nationalite :"Falkland"},
    { codeNationalite:68, nationalite :"Feroe"},
    { codeNationalite:69, nationalite :"Fidji"},
    { codeNationalite:70, nationalite :"Finlande"},
    { codeNationalite:71, nationalite :"France"},
    { codeNationalite:72, nationalite :"Gabon"},
    { codeNationalite:73, nationalite :"Gambie"},
    { codeNationalite:74, nationalite :"Georgie"},
    { codeNationalite:75, nationalite :"Germany"},
    { codeNationalite:76, nationalite :"Ghana"},
    { codeNationalite:77, nationalite :"Gibraltar"},
    { codeNationalite:78, nationalite :"Grece"},
    { codeNationalite:79, nationalite :"Grenade"},
    { codeNationalite:80, nationalite :"Groenland"},
    { codeNationalite:81, nationalite :"Guadeloupe"},
    { codeNationalite:82, nationalite :"Guam"},
    { codeNationalite:83, nationalite :"Guatemala"},
    { codeNationalite:84, nationalite :"Guernesey"},
    { codeNationalite:85, nationalite :"Guinee"},
    { codeNationalite:86, nationalite :"Guinee_Bissau"},
    { codeNationalite:87, nationalite :"Guinee equatoriale"},
    { codeNationalite:88, nationalite :"Guyana"},
    { codeNationalite:89, nationalite :"Guyane_Francaise "},
  { codeNationalite:90, nationalite :"Haiti" },
 { codeNationalite:91, nationalite :"Hawaii" },
 { codeNationalite:92, nationalite :"Honduras"},
 { codeNationalite:93, nationalite :"Hong_Kong"},
 { codeNationalite:94, nationalite :"Hongrie"},
{ codeNationalite:95, nationalite :"Inde"},
{ codeNationalite:96, nationalite :"Indonesie"},
{ codeNationalite:97, nationalite :"Iran"},
{ codeNationalite:98, nationalite :"Iraq"},
{ codeNationalite:99, nationalite :"Irlande"},
{ codeNationalite:100, nationalite :"Islande"},
{ codeNationalite:101, nationalite :"Israel"},
{ codeNationalite:102, nationalite :"Italie"},
{ codeNationalite:103, nationalite :"Jamaique"},
{ codeNationalite:104, nationalite :"Jan Mayen"},
{ codeNationalite:105, nationalite :"Japon"},
{ codeNationalite:106, nationalite :"Jersey"},
{ codeNationalite:107, nationalite :"Jordanie"},
{ codeNationalite:108, nationalite :"Kazakhstan"},
{ codeNationalite:109, nationalite :"Kenya"},
{ codeNationalite:110, nationalite :"Kirghizstan"},
{ codeNationalite:111, nationalite :"Kiribati"},
{ codeNationalite:112, nationalite :"Koweit"},
{ codeNationalite:113, nationalite :"Laos"},
{ codeNationalite:114, nationalite :"Lesotho"},
{ codeNationalite:115, nationalite :"Lettonie"},
{ codeNationalite:116, nationalite :"Liban"},
{ codeNationalite:117, nationalite :"Liberia"},
{ codeNationalite:118, nationalite :"Liechtenstein"},
{ codeNationalite:119, nationalite :"Lituanie"},
{ codeNationalite:120, nationalite :"Luxembourg"},
{ codeNationalite:121, nationalite :"Lybie"},
{ codeNationalite:122, nationalite :"Macao"},
{ codeNationalite:123, nationalite :"Macedoine"},
{ codeNationalite:124, nationalite :"Madagascar"},
{ codeNationalite:125, nationalite :"Madère"},
{ codeNationalite:126, nationalite :"Malaisie"},
{ codeNationalite:127, nationalite :"Malawi"},
{ codeNationalite:128, nationalite :"Maldives"},
{ codeNationalite:129, nationalite :"Mali"},
{ codeNationalite:130, nationalite :"Malte"},
{ codeNationalite:131, nationalite :"Man"},
{ codeNationalite:132, nationalite :"Mariannes du Nord"},
{ codeNationalite:133, nationalite :"Maroc"},
{ codeNationalite:134, nationalite :"Marshall"},
{ codeNationalite:135, nationalite :"Martinique"},
{ codeNationalite:136, nationalite :"Maurice"},
{ codeNationalite:137, nationalite :"Mauritanie"},
{ codeNationalite:138, nationalite :"Mayotte"},
{ codeNationalite:139, nationalite :"Mexique"},
{ codeNationalite:140, nationalite :"Micronesie"},
{ codeNationalite:141, nationalite :"Midway"},
{ codeNationalite:142, nationalite :"Moldavie"},
{ codeNationalite:143, nationalite :"Monaco"},
{ codeNationalite:144, nationalite :"Mongolie"},
{ codeNationalite:145, nationalite :"Montserrat"},
{ codeNationalite:146, nationalite :"Mozambique"},
{ codeNationalite:147, nationalite :"Namibie"},
{ codeNationalite:148, nationalite :"Nauru"},
{ codeNationalite:149, nationalite :"Nepal"},
{ codeNationalite:150, nationalite :"Nicaragua"},
{ codeNationalite:151, nationalite :"Niger"},
{ codeNationalite:152, nationalite :"Nigeria"},
{ codeNationalite:153, nationalite :"Niue"},
{ codeNationalite:154, nationalite :"Norfolk"},
{ codeNationalite:155, nationalite :"Norvege"},
{ codeNationalite:156, nationalite :"Nouvelle_Caledonie"},
{ codeNationalite:157, nationalite :"Nouvelle_Zelande"},
{ codeNationalite:158, nationalite :"Oman"},
{ codeNationalite:159, nationalite :"Ouganda"},
{ codeNationalite:160, nationalite :"Ouzbekistan"},
{ codeNationalite:161, nationalite :"Pakistan"},
{ codeNationalite:162, nationalite :"Palau"},
{ codeNationalite:163, nationalite :"Palestine"},
{ codeNationalite:164, nationalite :"Panama"},
{ codeNationalite:165, nationalite :"Papouasie_Nouvelle_Guinee"},
{ codeNationalite:166, nationalite :"Paraguay"},
{ codeNationalite:167, nationalite :"Pays_Bas"},
{ codeNationalite:168, nationalite :"Perou"},
{ codeNationalite:169, nationalite :"Philippines"},
{ codeNationalite:170, nationalite :"Pologne"},
{ codeNationalite:171, nationalite :"Polynesie"},
{ codeNationalite:172, nationalite :"Porto_Rico"},
{ codeNationalite:173, nationalite :"Portugal"},
{ codeNationalite:174, nationalite :"Qatar"},
{ codeNationalite:175, nationalite :"Republique_Dominicaine"},
{ codeNationalite:176, nationalite :"Republique_Tcheque"},
{ codeNationalite:177, nationalite :"Reunion"},
{ codeNationalite:178, nationalite :"Roumanie"},
{ codeNationalite:179, nationalite :"Royaume_Uni"},
{ codeNationalite:180, nationalite :"Russie"},
{ codeNationalite:181, nationalite :"Rwanda"}, 
{ codeNationalite:182, nationalite :"Sahara Occidental"},
{ codeNationalite:183, nationalite :"Sainte_Lucie"},
{ codeNationalite:184, nationalite :"Saint_Marin"},
{ codeNationalite:185, nationalite :"Salomon"},
{ codeNationalite:186, nationalite :"Salvador"},
{ codeNationalite:187, nationalite :"Samoa_Occidentales"},
{ codeNationalite:188, nationalite :"Samoa_Americaine"},
{ codeNationalite:189, nationalite :"Sao_Tome_et_Principe"},
{ codeNationalite:190, nationalite :"Senegal"},
{ codeNationalite:191, nationalite :"Seychelles"},
{ codeNationalite:192, nationalite :"Sierra Leone"},
{ codeNationalite:193, nationalite :"Singapour"},
{ codeNationalite:194, nationalite :"Slovaquie"},
{ codeNationalite:195, nationalite :"Slovenie"},
{ codeNationalite:196, nationalite :"Somalie"},
{ codeNationalite:197, nationalite :"Soudan"},
{ codeNationalite:198, nationalite :"Sri_Lanka"},
{ codeNationalite:199, nationalite :"Suede"},
{ codeNationalite:200, nationalite :"Suisse"},
{ codeNationalite:201, nationalite :"Surinam"},
{ codeNationalite:202, nationalite :"Swaziland"},
{ codeNationalite:203, nationalite :"Syrie"},
{ codeNationalite:204, nationalite :"Tadjikistan"},
{ codeNationalite:205, nationalite :"Taiwan"},
{ codeNationalite:206, nationalite :"Tonga"},
{ codeNationalite:207, nationalite :"Tanzanie"},
{ codeNationalite:208, nationalite :"Tchad"},
{ codeNationalite:209, nationalite :"Thailande"},
{ codeNationalite:210, nationalite :"Tibet"},
{ codeNationalite:211, nationalite :"Timor_Oriental"},
{ codeNationalite:212, nationalite :"Togo"},
{ codeNationalite:213, nationalite :"Trinite_et_Tobago"},
{ codeNationalite:214, nationalite :"Tristan da cunha"},
{ codeNationalite:215, nationalite :"Tunisie"},
{ codeNationalite:216, nationalite :"Turkmenistan"},
{ codeNationalite:217, nationalite :"Turquie"},
{ codeNationalite:218, nationalite :"Ukraine"},
{ codeNationalite:219, nationalite :"Uruguay"},
{ codeNationalite:220, nationalite: "Vanuatu"},
{ codeNationalite:221, nationalite :"Vatican"},
{ codeNationalite:222, nationalite :"Venezuela"},
{ codeNationalite:223, nationalite :"Vierges_Americaines"},
{ codeNationalite:224, nationalite :"Vierges_Britanniques"},
{ codeNationalite:225, nationalite :"Vietnam"},
{ codeNationalite:226, nationalite :"Wake"},
{ codeNationalite:227, nationalite :"Wallis et Futuma"},
{ codeNationalite:228, nationalite :"Yemen"},
{ codeNationalite:229, nationalite :"Yougoslavie"},
{ codeNationalite:230, nationalite :"Zambie"},
{ codeNationalite:231, nationalite :"Zimbabwe"}
    
 ];
