import { profession } from "./profession";

export const listeProfession : profession[] = [
    { name: 'Architecte' },
    {  name: 'Artisan' },
    {  name: 'Auteur' },
    {  name: 'Agent immobilier'},
    {  name: 'Agent du location'},
    {  name: 'Agent de joueurs' },
    {name: 'Avocat'},
    {  name: 'Artiste'},
    {  name: 'Boulanger' },
    {  name: 'Biologiste'},
    {  name: 'Chauffeur' },
    {  name: 'Comedien'},
    {  name: 'Comptable' },
    {  name: 'Concierge'},
    {  name: 'Comedien'},
    {  name: 'Conseiller'},
    {  name: 'Cuisinier' },
    {  name: 'Caissier'},
    {  name: 'Chef projet'},
    {  name: 'Chef d agence'},
    {  name: 'Casinos'},
    {  name: 'Commercant'},
    {  name: 'Directeur'},
    {  name: 'Developpeur'},
    {  name: 'Enseignant' },
    {  name: 'Formateur' },
    {  name: 'Geographe' },
    {  name: 'Gerant' },
    {  name: 'Graphiste'},
    {  name: 'Guide'},
    {  name: 'Illustrateur'},
    {  name: 'Infermier' },
    {  name: 'Ingenieur' },
    {  name: 'Jardinier'},
    {  name: 'Libraire'},
    {  name: 'Médecin'},
    {  name: 'Realisateur'}, 
    {  name: 'Responsable ressource humaine' },
    {  name: 'Serveur'},
    {  name: 'Traducteur'},
    {  name: 'Vendeur'},
    {  name: 'Vendeurs et revendeur de bateaux'},
    {  name: 'Homme d affaire'},
    {  name: 'Femme d affaire' },
    {  name: 'Sans Activite'},   
    {  name: 'Tresorier d une association' },
    {  name: 'President d une association'},


]