import { secteur } from "./secteur";

export const listeSecteur : secteur[] = [
        { name: 'Agroalimentaire' },
        {  name: 'Assurance' },
        {  name: 'Automobile-Reparation automobiles' },
        {  name: 'Arment'},
        {  name: 'Banque'},
        {  name: 'Bois-Carton' },
        {  name: 'BTP-Materiaux de construction' },
        {  name: 'Bureaux de change'},
        {  name: 'Chaussure' },
        { name: 'Clubs VIP'},
        {  name: 'Casinos'},
        {  name: 'Commerce'},
        {  name: 'Chimie-Parachimie' },
        {  name: 'Distribution'},
        { name: 'Droit'},
        {  name: 'Electronique' },
        {  name: 'Ecletricite' },
        {  name: 'Enseignement' },
        {  name: 'Environnement' },
        {  name: 'Etudes et conseils'},
        {  name: 'Etablissement de jeux de hasard'},
        {  name: 'Hotellerie-Restauration'},
        {  name: 'Industrie pharmaceutique' },
        {  name: 'Machine et equipement' },
        {  name: 'Marketing'},
        {  name: 'Metaux et pierres precieuse'},
        {  name: 'Métallurgie-Travail du métal'},
        {  name: 'Informatique-Telecoms'},
        {  name: 'Import-Export'},
        {  name: 'Industrie petro-chimique'},
        {  name: 'Immobilier'},
        {  name: 'Industrie'},
        {  name: 'Jeu Video'},
        {  name: 'Journalisme'},
        {  name: 'Langues'},
        {  name: 'Papier-Imprimerie' },
        { name: 'Petrole'},
        {  name: 'Plastique-Caoutchouc' },
        {  name: 'Ressource Humaine' },
        {  name: 'Relations d’affaire avec etats ou gouvernements etrangers'},
        {  name: 'Services aux entreprises'},
        { name: 'Textile-Habillement' },
        {  name: 'Transport maritime'},
        {  name: 'Tourisme'},
        {  name: 'Transport-Logistique'},
       
      ];
    
